version: '3.4'

services:


  deepstream:
    environment:
    #- FEEDS=/Dataset/sample_720p.mp4 
    - FEEDS=/Dataset/video.mp4,/Dataset/video.mp4,/Dataset/video.mp4,/Dataset/video.mp4
    #,/Dataset/video.mp4
    # - FEEDS=/Dataset/1.jpeg  
    - MINIOURL=http://minio:9000
    ports:
    - "2060:2060"

  deepstream-dapr:
    command: [ "./daprd", "-app-id", "deepstream","--app-protocol", "grpc", "--app-port", "2060","--dapr-http-port", "3500", "-components-path", "/components" ]
    volumes:
    - "./dapr/components/:/components"


  rulesengine:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  rulesengine-dapr:
    command: [ "./daprd", "-app-id", "rulesengine", "-app-port", "80", "-components-path", "/components"]
    volumes:
    - "./dapr/components/:/components"


  alerts-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "50064:80"

  alertsapi-dapr:
    command: [ "./daprd", "-app-id", "alerts-api", "-app-port", "80", "-components-path", "/components", "--dapr-http-max-request-size", "50"]
    volumes:
    - "./dapr/components/:/components"

  alerts-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "50052:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  alerts-ui-dapr:
    command: [ "./daprd", "-app-id", "alerts-ui", "-app-port", "80", "--dapr-http-max-request-size","50"]

  files-management:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Minio:Username=minio
      - Minio:Password=minio123
      - Minio:ServiceUrl=http://minio:9000

    ports:
      - "50059:80"

  files-management-dapr:
    command: [ "./daprd", "-app-id", "files-management", "-app-port", "80", "-components-path", "/components", "--dapr-http-max-request-size", "50"]
    volumes:
    - "./dapr/components/:/components"

  mosquitto:
    ports:
      - '1883:1883'

  mongodb:
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - './mongodb/database:/data/db'
    ports:
    - 27027:27027
    restart: "unless-stopped"
