apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfrontend
  namespace: dapr-k8s-poc
  labels:
    app: myfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfrontend
  template:
    metadata:
      labels:
        app: myfrontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "myfrontend"
        dapr.io/app-port: "80"
        dapr.io/enable-profiling: "true"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: myfrontend
        image: cesardl/myfrontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+:80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: myfrontend
  name: myfrontend
  namespace: dapr-k8s-poc
spec:
  type: LoadBalancer
  selector:
    app: myfrontend
  ports:
  - protocol: TCP
    port: 88
    targetPort: 80
