apiVersion: apps/v1
kind: Deployment
metadata:
  name: rulesengine
  namespace: mec-accelerator
  labels:
    app: rulesengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rulesengine
  template:
    metadata:
      labels:
        app: rulesengine
    spec:
      containers:
      - name: rulesengine
        image: mecsolutionaccelerator/rulesengine:1.9
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
        envFrom:
        - configMapRef:
            name: mqtt-config
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rulesengine
  name: rulesengine
  namespace: mec-accelerator
spec:
  type: NodePort
  ports:
  - name: "web"
    port: 8080
    targetPort: 80
    nodePort: 30003
  selector:
    app: rulesengine
