apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-plane-mongodb-data
  namespace: mec-accelerator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane-mongodb-deployment
  namespace: mec-accelerator
spec:
  selector:
    matchLabels:
      app: control-plane-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: control-plane-mongodb
    spec:
      hostname: mongo
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: control-plane-mongodb-data
---

apiVersion: v1
kind: Service
metadata:
  name: control-plane-mongodb
  namespace: mec-accelerator
spec:
  selector:
    app: control-plane-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP