apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame-splitter
  # namespace: mec-core
  labels:
    app: frame-splitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frame-splitter
  template:
    metadata:
      labels:
        app: frame-splitter
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frame-splitter"
        dapr.io/app-protocol: "grpc"
        # dapr.io/app-port: "50052"
        dapr.io/log-level: "debug"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: frame-splitter
        image: javipercor/framesplitter:latest
        ports:
        - containerPort: 50052
        imagePullPolicy: Always
        env:
          - name: FEED
            value: "rtsp://0.tcp.ngrok.io:13571/mystream"
          - name: TIMEOUT
            value: "15"
