apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepstream
  namespace: mec-accelerator
  labels:
    app: deepstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepstream
  template:
    metadata:
      labels:
        app: deepstream
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "deepstream"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "debug"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: deepstream
        image: mecsolutionaccelerator/deepstream:0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: MINIOURL
            value: "http://minio.mec-accelerator.svc.cluster.local:9000"
          - name: FEEDS
            value: "/Dataset/PerimeterDemo.mp4" # Video source. Change this for a real RTSP uri like "rtsp://x.x.x.x:8554/mystream"
        resources:
          limits:
           nvidia.com/gpu: 1
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
