/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,vue}"],
  theme: {
    colors: {
      navBar: '#777777',
      darkGray: '#343333',
      bgFrom: '#9E9E9E',
      bgTo: '#FFFFFF',
      selected: '#B9B9B9',
      click: '#d1d5db',
      mWhite: '#F3F3F3',
      robotSelected: '#427FC9',
      robotActive: '#1A57A1',
      tableHeader: '#8CA9BF',
      tableData: '#FFFFFF',
      green: '#22c55e',
      red: '#dc2626',
      darkRed: '#721C24',
      yellow: '#EAB308',
      darkYellow: '#856404',
      buttonGray: '#38495C',
      buttonDisabled: '#98A2AC',
      videoSearch: '#9DA3AE',
      routeSelected: '#E3F8FF',
    },
    extend: {},
  },
  plugins: [],
}
